improved readability.

diff --git a/tbd b/tbd
--- a/tbd
+++ b/tbd
@@ -1,27 +1,24 @@
 #! /bin/bash
 
-ignore_errors: () { __x=${1}; }
-tc () { 2> "${__et:=$(mktemp)}" "$@"; }
-qq () { > /dev/null tc "$@"; }
+shopt -s expand_aliases; alias null='> /dev/null 2> "${__err_t:=$(mktemp)}" ' \
+                               trace='2> "${__err_t:=$(mktemp)}" ' \
+                               say='printf "\r\e[%sm %s\e[0m\n"'
 
-@ () { printf "\e[1m\n$*\e[0m\n"; }
-
-::et () { sed "s|^|    > |" "$__et"; exit 1; }
-::no () { ((__no++)); printf "\r\e[31m  !!\e[0m\n"; ${__x:-false} || ::et; }
-::ok () { ((__ok++)); printf "\r\e[32m  ok\e[0m\n"; }
+@ () { printf "\n\e[1m-- ${*}\e[0m\n"; }
 
 - () {
-    ((__tt++)); printf "%6s'${1}' ${*:2}"
+    ((__tt++)); printf "%4s\`${1}\` ${*:2}"
 
-    case "$2" in ( works  )  qq eval "$1";;
-                 ( fails  )  qq eval "! $1";;
-                 ( prints )  test "$(tc eval "$1")" = "$3";;
-                 ( * )       qq "$2" "$1" "${@:3}";;
-    esac \
-        && ::ok || ::no
+    case "$2" in ( works  )  null eval "$1";;
+                 ( fails  )  null eval "! $1";;
+                 ( prints )  test "$(trace eval "$1")" = "$3";;
+                 ( * )       null "$2" "$1" "${@:3}";; esac
+
+    case $? in ( 0 )  ((__ok++)); say 32 "ok";;
+               ( * )  ((__no++)); say 31 "!!"; sed 's/^/    | /' "$__err_t"; exit 1;; esac
 }
 
-trap 'printf "\n\e[3m  ${__tt:-0} tests executed, ${__ok:-0} passed, ${__no:-0} failed.\e[0m\n\n"; rm "$__et"' \
-    EXIT
+trap 'rm -f "$__err_t"; printf "\n\e[3m  ${__tt:-0} tests, ${__ok:-0} ok, ${__no:-0} failed.\e[0m\n\n"' \
+      EXIT
 
-for _ in "${@:-testfile}"; do source "$_"; done
+for _ in "${@:-testfile}"; do trace source "$_"; done
